steps:
  prettier_check:
    image: tmknom/prettier:3.2.5
    commands:
      - prettier -c .
    when:
      - event: pull_request

  build_typescript_plugin:
    image: node:22-bookworm-slim
    commands:
      - apt-get update && apt-get install -y --no-install-recommends --no-install-suggests typescript
      - wget --quiet https://github.com/extism/js-pdk/releases/download/v1.4.0/extism-js-x86_64-linux-v1.4.0.gz -O extism-js.gz
      - gzip -d extism-js.gz
      - chmod +x extism-js
      - mv extism-js /usr/local/bin/
      - ls -la /usr/local/bin/extism-js
      - cd plugins/typescript_push_webhook
      - npm install
      - extism-js --help
      - npm run build
    when:
      - event: [pull_request, tag]

  build_go_plugin:
    image: tinygo/tinygo:latest
    backend_options:
      docker:
        user: 0:0
    commands:
      - cd plugins/go_replace_words
      - tinygo build -o ../go_replace_words.wasm -target wasip1 -buildmode=c-shared main.go
    when:
      - event: [pull_request, tag]

  run_plugin_tests:
    image: node:22-bookworm-slim
    environment:
      LEMMY_DATABASE_URL: postgres://lemmy:password@database:5432
      DO_WRITE_HOSTS_FILE: "1"
    commands:
      - npm install -g corepack@latest && corepack enable pnpm
      - apt-get update && apt-get install -y --no-install-recommends --no-install-suggests bash curl postgresql-client golang wget ca-certificates
      # install tinygo to compile wasm plugins
      # https://tinygo.org/getting-started/install/linux/#ubuntu-debian
      - wget -q https://github.com/tinygo-org/tinygo/releases/download/v0.36.0/tinygo_0.36.0_amd64.deb
      - dpkg -i tinygo_0.36.0_amd64.deb
      - bash tests/prepare.sh
      - cd tests/
      - pnpm i
      - pnpm test
    when:
      - event: pull_request

  publish_plugins:
    image: woodpeckerci/plugin-release
    settings:
      files:
        - plugins/go_replace_words.wasm
        - plugins/typescript_push_webhook.wasm
      title: ${CI_COMMIT_TAG##v}
      api-key:
        from_secret: github_token
    when:
      - event: tag

services:
  database:
    # 15-alpine image necessary because of diesel tests
    image: pgautoupgrade/pgautoupgrade:15-alpine
    environment:
      POSTGRES_DB: lemmy
      POSTGRES_USER: lemmy
      POSTGRES_PASSWORD: password
